[[microprofile]]
== Microprofile Specification Dependencies Mapping

This section details all dependencies related to Microprofile.

[[MicroProfile-Telemetry]]
=== `MicroProfile-Telemetry`

[[microprofile-telemetry]]
==== *microprofile-telemetry*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-telemetry</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-telemetry]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-telemetry*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - telemetry (opentelemetry tracing)</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-telemetry</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[MicroProfile-Open-API]]
=== `MicroProfile-Open-API`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-openapi-api]]
==== *microprofile-openapi-api*
**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>3.1.1</version>
</dependency>
----
[[org.eclipse.microprofile.openapi]]
==== *org.eclipse.microprofile.openapi*
**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>microprofile openapi bundle</groupId>
    <artifactId>org.eclipse.microprofile.openapi</artifactId>
    <version>3.1.1</version>
</dependency>
----
[[microprofile-opentracing-api]]
==== *microprofile-opentracing-api*
**Version**: 3.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.opentracing</groupId>
    <artifactId>microprofile-opentracing-api</artifactId>
    <version>3.0</version>
</dependency>
----
[[org.eclipse.microprofile.opentracing]]
==== *org.eclipse.microprofile.opentracing*
**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>microprofile opentracing bundle</groupId>
    <artifactId>org.eclipse.microprofile.opentracing</artifactId>
    <version>3.0.0</version>
</dependency>
----
[[microprofile-openapi]]
==== *microprofile-openapi*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-openapi</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-openapi]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-openapi*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - openapi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-openapi</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[MicroProfile-Rest-Client]]
=== `MicroProfile-Rest-Client`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.microprofile.]]
==== *org.glassfish.jersey.ext.microprofile.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-mp-rest-client</groupId>
    <artifactId>org.glassfish.jersey.ext.microprofile.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[microprofile-rest-client-api]]
==== *microprofile-rest-client-api*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.rest.client</groupId>
    <artifactId>microprofile-rest-client-api</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[org.eclipse.microprofile.rest.client]]
==== *org.eclipse.microprofile.rest.client*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>microprofile rest client bundle</groupId>
    <artifactId>org.eclipse.microprofile.rest.client</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[microprofile-rest-client]]
==== *microprofile-rest-client*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-rest-client</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile rest client</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[MicroProfile-Config]]
=== `MicroProfile-Config`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-config-api]]
==== *microprofile-config-api*
**Version**: 3.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.config</groupId>
    <artifactId>microprofile-config-api</artifactId>
    <version>3.1</version>
</dependency>
----
[[org.eclipse.microprofile.config]]
==== *org.eclipse.microprofile.config*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>microprofile config api</groupId>
    <artifactId>org.eclipse.microprofile.config</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[microprofile-config]]
==== *microprofile-config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-config]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile-config</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-config-extensions]]
==== *microprofile-config-extensions*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config-extensions</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile-config-extensions</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-config-service]]
==== *microprofile-config-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>microprofile-config-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.microprofile-config-service]]
==== *fish.payara.server.internal.payara-modules.microprofile-config-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile config service</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.microprofile-config-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[MicroProfile-Fault-Tolerance]]
=== `MicroProfile-Fault-Tolerance`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-fault-tolerance]]
==== *microprofile-fault-tolerance*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-fault-tolerance</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - fault tolerance</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-fault-tolerance-api]]
==== *microprofile-fault-tolerance-api*
**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.fault-tolerance</groupId>
    <artifactId>microprofile-fault-tolerance-api</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----
[[org.eclipse.microprofile.fault.tolerance]]
==== *org.eclipse.microprofile.fault.tolerance*
**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>microprofile-fault-tolerance-api</groupId>
    <artifactId>org.eclipse.microprofile.fault.tolerance</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----
[[MicroProfile-Metrics]]
=== `MicroProfile-Metrics`

[[microprofile-metrics]]
==== *microprofile-metrics*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-metrics</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-metrics]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-metrics*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - metrics</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-metrics</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-metrics-api]]
==== *microprofile-metrics-api*
**Version**: 5.1.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.metrics</groupId>
    <artifactId>microprofile-metrics-api</artifactId>
    <version>5.1.0.payara-p1</version>
</dependency>
----
[[org.eclipse.microprofile.metrics]]
==== *org.eclipse.microprofile.metrics*
**Version**: 5.1.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>microprofile metrics bundle</groupId>
    <artifactId>org.eclipse.microprofile.metrics</artifactId>
    <version>5.1.0.payara-p1</version>
</dependency>
----
[[MicroProfile-JWT-Authentication]]
=== `MicroProfile-JWT-Authentication`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-jwt-auth-api]]
==== *microprofile-jwt-auth-api*
**Version**: 2.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.jwt</groupId>
    <artifactId>microprofile-jwt-auth-api</artifactId>
    <version>2.1</version>
</dependency>
----
[[microprofile-jwt-auth]]
==== *microprofile-jwt-auth*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-jwt-auth</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-jwt-auth]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-jwt-auth*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - jwt</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-jwt-auth</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[MicroProfile-Health]]
=== `MicroProfile-Health`

[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[]]
==== **
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-health-api]]
==== *microprofile-health-api*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.health</groupId>
    <artifactId>microprofile-health-api</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[org.eclipse.microprofile.health]]
==== *org.eclipse.microprofile.health*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>microprofile health check bundle</groupId>
    <artifactId>org.eclipse.microprofile.health</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[microprofile-healthcheck]]
==== *microprofile-healthcheck*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-healthcheck</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>microprofile - healthcheck</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck</artifactId>
    <version>6.18.0</version>
</dependency>
----
