[[internals]]
== Payara Platform Internal Mappings

This section details all dependencies related to internal modules, extensions, plugins and other extras.

[[payara-internal]]
=== `payara-internal`

[[org.jxmpp.jid]]
==== *org.jxmpp.jid*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-jid</groupId>
    <artifactId>org.jxmpp.jid</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[org.jxmpp.jid]]
==== *org.jxmpp.jid*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-jid</groupId>
    <artifactId>org.jxmpp.jid</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[org.igniterealtime.smack.tcp]]
==== *org.igniterealtime.smack.tcp*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-tcp</groupId>
    <artifactId>org.igniterealtime.smack.tcp</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[org.igniterealtime.smack.im]]
==== *org.igniterealtime.smack.im*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-im</groupId>
    <artifactId>org.igniterealtime.smack.im</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[org.igniterealtime.smack.java7]]
==== *org.igniterealtime.smack.java7*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-java7</groupId>
    <artifactId>org.igniterealtime.smack.java7</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[xmpp-notifier-console-plugin]]
==== *xmpp-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>xmpp-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.xmpp-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.xmpp-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>xmpp notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.xmpp-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[org.jxmpp.core]]
==== *org.jxmpp.core*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-core</groupId>
    <artifactId>org.jxmpp.core</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[org.jxmpp.core]]
==== *org.jxmpp.core*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-core</groupId>
    <artifactId>org.jxmpp.core</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[org.igniterealtime.smack.core]]
==== *org.igniterealtime.smack.core*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-core</groupId>
    <artifactId>org.igniterealtime.smack.core</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[xmpp-notifier-core]]
==== *xmpp-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>xmpp-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.xmpp-notifier-core]]
==== *fish.payara.extensions.notifiers.xmpp-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>xmpp notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.xmpp-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[org.igniterealtime.smack.extensions]]
==== *org.igniterealtime.smack.extensions*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-extensions</groupId>
    <artifactId>org.igniterealtime.smack.extensions</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[org.jxmpp.util-cache]]
==== *org.jxmpp.util-cache*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-util-cache</groupId>
    <artifactId>org.jxmpp.util-cache</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[org.jxmpp.util-cache]]
==== *org.jxmpp.util-cache*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-util-cache</groupId>
    <artifactId>org.jxmpp.util-cache</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[hazelcast-bootstrap]]
==== *hazelcast-bootstrap*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>hazelcast-bootstrap</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.hazelcast-bootstrap]]
==== *fish.payara.server.core.payara-modules.hazelcast-bootstrap*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>payara hazelcast bootstrap</groupId>
    <artifactId>fish.payara.server.core.payara-modules.hazelcast-bootstrap</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-xml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-xml*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-xml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-xml</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[fish.payara.server.internal.jms.handlers]]
==== *fish.payara.server.internal.jms.handlers*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms annotation handlers</groupId>
    <artifactId>fish.payara.server.internal.jms.handlers</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[admin-util]]
==== *admin-util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>admin-util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.util]]
==== *fish.payara.server.core.admin.util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-util</groupId>
    <artifactId>fish.payara.server.core.admin.util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[nimbus-jose-jwt]]
==== *nimbus-jose-jwt*
**Version**: 9.40

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>9.40</version>
</dependency>
----
[[gson]]
==== *gson*
**Version**: 2.11.0

[source,xml]
----
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.11.0</version>
</dependency>
----
[[com.nimbusds.nimbus-jose-jwt]]
==== *com.nimbusds.nimbus-jose-jwt*
**Version**: 9.40.0

[source,xml]
----
<dependency>
    <groupId>nimbus jose+jwt</groupId>
    <artifactId>com.nimbusds.nimbus-jose-jwt</artifactId>
    <version>9.40.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.common]]
==== *fish.payara.server.internal.persistence.common*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>common persistence code between jpa and cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.common</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>cdi apis</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[fish.payara.server.internal.batch.glassfish-batch-connector]]
==== *fish.payara.server.internal.batch.glassfish-batch-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>batch connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.batch.glassfish-batch-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.extensions.notifiers.email-notifier-core]]
==== *fish.payara.extensions.notifiers.email-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>email notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.email-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[hk2-runlevel]]
==== *hk2-runlevel*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-runlevel</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[web-glue]]
==== *web-glue*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-glue</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.glue]]
==== *fish.payara.server.core.web.glue*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>web container glue code</groupId>
    <artifactId>fish.payara.server.core.web.glue</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[glassfish-naming]]
==== *glassfish-naming*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>glassfish-naming</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.glassfish-naming]]
==== *fish.payara.server.core.common.glassfish-naming*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish naming</groupId>
    <artifactId>fish.payara.server.core.common.glassfish-naming</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils]]
==== *fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara jaspic servlet utilities</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.asadmin-audit]]
==== *fish.payara.server.internal.payara-modules.asadmin-audit*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara asadmin auditor</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.asadmin-audit</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 6.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>6.0.0</version>
</dependency>
----
[[console-corba-plugin]]
==== *console-corba-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-corba-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-corba-plugin]]
==== *fish.payara.server.internal.admingui.console-corba-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console corba plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-corba-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.hk2.runlevel]]
==== *org.glassfish.hk2.runlevel*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>run level service</groupId>
    <artifactId>org.glassfish.hk2.runlevel</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[class-model]]
==== *class-model*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>class-model</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.class-model]]
==== *org.glassfish.hk2.class-model*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>class model for hk2</groupId>
    <artifactId>org.glassfish.hk2.class-model</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-multipart</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.batch.glassfish-batch-commands]]
==== *fish.payara.server.internal.batch.glassfish-batch-commands*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>batch commands for glassfish</groupId>
    <artifactId>fish.payara.server.internal.batch.glassfish-batch-commands</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-full-container]]
==== *fish.payara.server.internal.ejb.ejb-full-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>full ejb container add-ons</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-full-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[ha-file-store]]
==== *ha-file-store*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ha</groupId>
    <artifactId>ha-file-store</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.ha.ha-file-store]]
==== *fish.payara.server.internal.ha.ha-file-store*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish ha-file-store</groupId>
    <artifactId>fish.payara.server.internal.ha.ha-file-store</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.transformer.payara]]
==== *fish.payara.transformer.payara*
**Version**: 0.2.12

[source,xml]
----
<dependency>
    <groupId>fish.payara.transformer</groupId>
    <artifactId>fish.payara.transformer.payara</artifactId>
    <version>0.2.12</version>
</dependency>
----
[[org.eclipse.persistence.moxy]]
==== *org.eclipse.persistence.moxy*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink moxy</groupId>
    <artifactId>org.eclipse.persistence.moxy</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[fish.payara.transformer.payara]]
==== *fish.payara.transformer.payara*
**Version**: 0.2.12

[source,xml]
----
<dependency>
    <groupId>fish.payara.transformer:fish.payara.transformer.payara</groupId>
    <artifactId>fish.payara.transformer.payara</artifactId>
    <version>0.2.12</version>
</dependency>
----
[[orb-enabler]]
==== *orb-enabler*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.orb</groupId>
    <artifactId>orb-enabler</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.orb.enabler]]
==== *fish.payara.server.core.orb.enabler*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish orb enabler implementation</groupId>
    <artifactId>fish.payara.server.core.orb.enabler</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.expressly]]
==== *org.glassfish.expressly*
**Version**: 5.0.0

[source,xml]
----
<dependency>
    <groupId>eclipse expressly</groupId>
    <artifactId>org.glassfish.expressly</artifactId>
    <version>5.0.0</version>
</dependency>
----
[[ldapbp-repackaged]]
==== *ldapbp-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>ldapbp-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.jxmpp.jid]]
==== *org.jxmpp.jid*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-jid</groupId>
    <artifactId>org.jxmpp.jid</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[fish.payara.server.core.packager.ldapbp-repackaged]]
==== *fish.payara.server.core.packager.ldapbp-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>ldapbp repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.ldapbp-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[osgi-container]]
==== *osgi-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.osgi-platforms</groupId>
    <artifactId>osgi-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.osgi-platforms.osgi-container]]
==== *fish.payara.server.internal.osgi-platforms.osgi-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>osgi container</groupId>
    <artifactId>fish.payara.server.internal.osgi-platforms.osgi-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.igniterealtime.smack.tcp]]
==== *org.igniterealtime.smack.tcp*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-tcp</groupId>
    <artifactId>org.igniterealtime.smack.tcp</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[rest-monitoring-service]]
==== *rest-monitoring-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>rest-monitoring-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.rest-monitoring-service]]
==== *fish.payara.server.internal.payara-appserver-modules.rest-monitoring-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>rest monitoring service</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.rest-monitoring-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-ee-api]]
==== *glassfish-ee-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>glassfish-ee-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[mimepull]]
==== *mimepull*
**Version**: 1.10.0

[source,xml]
----
<dependency>
    <groupId>org.jvnet.mimepull</groupId>
    <artifactId>mimepull</artifactId>
    <version>1.10.0</version>
</dependency>
----
[[fish.payara.server.core.common.glassfish-ee-api]]
==== *fish.payara.server.core.common.glassfish-ee-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>java ee dependent public apis of glassfish</groupId>
    <artifactId>fish.payara.server.core.common.glassfish-ee-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.jvnet.mimepull]]
==== *org.jvnet.mimepull*
**Version**: 1.10.0

[source,xml]
----
<dependency>
    <groupId>mime streaming extension</groupId>
    <artifactId>org.jvnet.mimepull</artifactId>
    <version>1.10.0</version>
</dependency>
----
[[monitoring-console-api]]
==== *monitoring-console-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.monitoring-console</groupId>
    <artifactId>monitoring-console-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[datadog-notifier-console-plugin]]
==== *datadog-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>datadog-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.monitoring-console.api]]
==== *fish.payara.monitoring-console.api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>monitoring-console-api</groupId>
    <artifactId>fish.payara.monitoring-console.api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[fish.payara.extensions.notifiers.datadog-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.datadog-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>datadog notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.datadog-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[jakarta.activation-api]]
==== *jakarta.activation-api*
**Version**: 2.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.1.3</version>
</dependency>
----
[[jakarta.activation-api]]
==== *jakarta.activation-api*
**Version**: 2.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta activation api</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.1.3</version>
</dependency>
----
[[org.eclipse.persistence.jpa.modelgen.processor]]
==== *org.eclipse.persistence.jpa.modelgen.processor*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa model generator</groupId>
    <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[jakarta.security.auth.message-api]]
==== *jakarta.security.auth.message-api*
**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta authentication</groupId>
    <artifactId>jakarta.security.auth.message-api</artifactId>
    <version>3.0.0</version>
</dependency>
----
[[fish.payara.server.internal.connectors.inbound-runtime]]
==== *fish.payara.server.internal.connectors.inbound-runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connectors inbound support</groupId>
    <artifactId>fish.payara.server.internal.connectors.inbound-runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.batch.payara-jbatch]]
==== *fish.payara.server.internal.batch.payara-jbatch*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ibm jbatch combined</groupId>
    <artifactId>fish.payara.server.internal.batch.payara-jbatch</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.7.0

[source,xml]
----
<dependency>
    <groupId>eclipselink asm</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.7.0</version>
</dependency>
----
[[payara-executor-service]]
==== *payara-executor-service*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>payara-executor-service</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.payara-executor-service]]
==== *fish.payara.server.core.payara-modules.payara-executor-service*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>payara executor service</groupId>
    <artifactId>fish.payara.server.core.payara-modules.payara-executor-service</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[common-util]]
==== *common-util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>common-util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.util]]
==== *fish.payara.server.core.common.util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>common utilities</groupId>
    <artifactId>fish.payara.server.core.common.util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jboss-logging]]
==== *jboss-logging*
**Version**: 3.6.0.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging</artifactId>
    <version>3.6.0.final</version>
</dependency>
----
[[org.glassfish.web.jakarta.servlet.jsp.jstl]]
==== *org.glassfish.web.jakarta.servlet.jsp.jstl*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta standard tag library implementation</groupId>
    <artifactId>org.glassfish.web.jakarta.servlet.jsp.jstl</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[com.fasterxml.jackson.core.]]
==== *com.fasterxml.jackson.core.*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson-databind</groupId>
    <artifactId>com.fasterxml.jackson.core.</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[org.jboss.logging.jboss-logging]]
==== *org.jboss.logging.jboss-logging*
**Version**: 3.6.0.final

[source,xml]
----
<dependency>
    <groupId>jboss logging 3</groupId>
    <artifactId>org.jboss.logging.jboss-logging</artifactId>
    <version>3.6.0.final</version>
</dependency>
----
[[org.apache.servicemix.bundles.xpp3]]
==== *org.apache.servicemix.bundles.xpp3*
**Version**: 1.1.4c_7

[source,xml]
----
<dependency>
    <groupId>org.apache.servicemix.bundles</groupId>
    <artifactId>org.apache.servicemix.bundles.xpp3</artifactId>
    <version>1.1.4c_7</version>
</dependency>
----
[[org.apache.servicemix.bundles.xpp3]]
==== *org.apache.servicemix.bundles.xpp3*
**Version**: 1.1.4.c

[source,xml]
----
<dependency>
    <groupId>apache servicemix :: bundles :: xpp3</groupId>
    <artifactId>org.apache.servicemix.bundles.xpp3</artifactId>
    <version>1.1.4.c</version>
</dependency>
----
[[monitoring-core]]
==== *monitoring-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>monitoring-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.monitoring-core]]
==== *fish.payara.server.core.admin.monitoring-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-monitoring</groupId>
    <artifactId>fish.payara.server.core.admin.monitoring-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[internal-api]]
==== *internal-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>internal-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.internal-api]]
==== *fish.payara.server.core.common.internal-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>private apis of glassfish</groupId>
    <artifactId>fish.payara.server.core.common.internal-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.jms.gf-jms-connector]]
==== *fish.payara.server.internal.jms.gf-jms-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms connector module for runtime</groupId>
    <artifactId>fish.payara.server.internal.jms.gf-jms-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.utility]]
==== *fish.payara.server.internal.persistence.cmp.utility*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>utility module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.utility</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[appclient-connector]]
==== *appclient-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.appclient.server</groupId>
    <artifactId>appclient-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.appclient.server.appclient-connector]]
==== *fish.payara.server.internal.appclient.server.appclient-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish appclient server-side connector</groupId>
    <artifactId>fish.payara.server.internal.appclient.server.appclient-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[dataprovider]]
==== *dataprovider*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admingui</groupId>
    <artifactId>dataprovider</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admingui.dataprovider]]
==== *fish.payara.server.core.admingui.dataprovider*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>dataprovider</groupId>
    <artifactId>fish.payara.server.core.admingui.dataprovider</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>opentracing jax-ws</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.generator-database]]
==== *fish.payara.server.internal.persistence.cmp.generator-database*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>database generator module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.generator-database</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.deployment.javaee-full]]
==== *fish.payara.server.internal.deployment.javaee-full*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>deployment related javaee full profile classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.javaee-full</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[newrelic-notifier-core]]
==== *newrelic-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>newrelic-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.newrelic-notifier-core]]
==== *fish.payara.extensions.notifiers.newrelic-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>new relic notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.newrelic-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.server.internal.security.appclient.security]]
==== *fish.payara.server.internal.security.appclient.security*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>appclient security integration</groupId>
    <artifactId>fish.payara.server.internal.security.appclient.security</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.resource-api]]
==== *jakarta.resource-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.resource</groupId>
    <artifactId>jakarta.resource-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[jakarta.resource-api]]
==== *jakarta.resource-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.resource api</groupId>
    <artifactId>jakarta.resource-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-sqlstore]]
==== *fish.payara.server.internal.persistence.cmp.support-sqlstore*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>support-sqlstore module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-sqlstore</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[json-smart]]
==== *json-smart*
**Version**: 2.5.1

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.5.1</version>
</dependency>
----
[[net.minidev.]]
==== *net.minidev.*
**Version**: 2.5.1

[source,xml]
----
<dependency>
    <groupId>json-smart</groupId>
    <artifactId>net.minidev.</artifactId>
    <version>2.5.1</version>
</dependency>
----
[[fish.payara.server.core.common.annotation-framework]]
==== *fish.payara.server.core.common.annotation-framework*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish java ee annotation framework</groupId>
    <artifactId>fish.payara.server.core.common.annotation-framework</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.eclipse.persistence.jpa.jpql]]
==== *org.eclipse.persistence.jpa.jpql*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink hermes parser</groupId>
    <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>4.0.2</version>
</dependency>
----
[[stats77]]
==== *stats77*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>stats77</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.]]
==== *fish.payara.server.core.common.*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>stats77</groupId>
    <artifactId>fish.payara.server.core.common.</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[glassfish]]
==== *glassfish*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.nucleus</groupId>
    <artifactId>glassfish</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.nucleus.glassfish]]
==== *fish.payara.server.core.nucleus.glassfish*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>appserver core bootstraping classes</groupId>
    <artifactId>fish.payara.server.core.nucleus.glassfish</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jdbc-admin]]
==== *jdbc-admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.jdbc.admin]]
==== *fish.payara.server.internal.jdbc.admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jdbc admin</groupId>
    <artifactId>fish.payara.server.internal.jdbc.admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.ws.rs-api]]
==== *jakarta.ws.rs-api*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta restful ws api</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[cluster-ssh]]
==== *cluster-ssh*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.cluster</groupId>
    <artifactId>cluster-ssh</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.cluster.ssh]]
==== *fish.payara.server.core.cluster.ssh*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>cluster ssh provisioning</groupId>
    <artifactId>fish.payara.server.core.cluster.ssh</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[dbschema]]
==== *dbschema*
**Version**: 6.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>dbschema</artifactId>
    <version>6.7</version>
</dependency>
----
[[org.glassfish.external.dbschema]]
==== *org.glassfish.external.dbschema*
**Version**: 6.7.0

[source,xml]
----
<dependency>
    <groupId>dbschema repackaged as an osgi bundle</groupId>
    <artifactId>org.glassfish.external.dbschema</artifactId>
    <version>6.7.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.model]]
==== *fish.payara.server.internal.persistence.cmp.model*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>model module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.model</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc]]
==== *org.glassfish.jersey.ext.jersey-mvc*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[glassfish-oracle-jdbc-driver-packages]]
==== *glassfish-oracle-jdbc-driver-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>glassfish-oracle-jdbc-driver-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.jms.gf-jms-injection]]
==== *fish.payara.server.internal.jms.gf-jms-injection*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms injection module for runtime</groupId>
    <artifactId>fish.payara.server.internal.jms.gf-jms-injection</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.osgi.util.promise]]
==== *org.osgi.util.promise*
**Version**: 1.3.0

[source,xml]
----
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.util.promise</artifactId>
    <version>1.3.0</version>
</dependency>
----
[[org.osgi.util.promise]]
==== *org.osgi.util.promise*
**Version**: 1.3.0.202212101352

[source,xml]
----
<dependency>
    <groupId>org.osgi:org.osgi.util.promise</groupId>
    <artifactId>org.osgi.util.promise</artifactId>
    <version>1.3.0.202212101352</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[console-cluster-plugin]]
==== *console-cluster-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-cluster-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-cluster-plugin]]
==== *fish.payara.server.internal.admingui.console-cluster-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console clustering support plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-cluster-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jansi-core]]
==== *jansi-core*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jansi-core</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-builtins]]
==== *jline-builtins*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-builtins</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-native]]
==== *jline-native*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-native</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-reader]]
==== *jline-reader*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-reader</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-remote-ssh]]
==== *jline-remote-ssh*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-remote-ssh</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-remote-telnet]]
==== *jline-remote-telnet*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-remote-telnet</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-style]]
==== *jline-style*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-style</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-terminal]]
==== *jline-terminal*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-terminal-ffm]]
==== *jline-terminal-ffm*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal-ffm</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-terminal-jansi]]
==== *jline-terminal-jansi*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal-jansi</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-terminal-jna]]
==== *jline-terminal-jna*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal-jna</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline-terminal-jni]]
==== *jline-terminal-jni*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal-jni</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[jline]]
==== *jline*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[org.jline]]
==== *org.jline*
**Version**: 3.26.3

[source,xml]
----
<dependency>
    <groupId>jline bundle</groupId>
    <artifactId>org.jline</artifactId>
    <version>3.26.3</version>
</dependency>
----
[[glassfish-javassist-packages]]
==== *glassfish-javassist-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>glassfish-javassist-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.core.glassfish-javassist-packages]]
==== *fish.payara.server.internal.core.glassfish-javassist-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish javassist packages</groupId>
    <artifactId>fish.payara.server.internal.core.glassfish-javassist-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[console-jts-plugin]]
==== *console-jts-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jts-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-jts-plugin]]
==== *fish.payara.server.internal.admingui.console-jts-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console jts plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-jts-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[soap-tcp]]
==== *soap-tcp*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>soap-tcp</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.webservices.soap-tcp]]
==== *fish.payara.server.internal.webservices.soap-tcp*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>soap/tcp integration code</groupId>
    <artifactId>fish.payara.server.internal.webservices.soap-tcp</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.gf-jpa-connector]]
==== *fish.payara.server.internal.persistence.gf-jpa-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connector for jpa runtime in glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.gf-jpa-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-jms-plugin]]
==== *fish.payara.server.internal.admingui.console-jms-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console jms plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-jms-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[ha-hazelcast-store]]
==== *ha-hazelcast-store*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ha</groupId>
    <artifactId>ha-hazelcast-store</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.ha.hazelcast-store]]
==== *fish.payara.server.internal.ha.hazelcast-store*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara ha hazelcast store</groupId>
    <artifactId>fish.payara.server.internal.ha.hazelcast-store</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.entitybean-container]]
==== *fish.payara.server.internal.persistence.entitybean-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>entity bean container</groupId>
    <artifactId>fish.payara.server.internal.persistence.entitybean-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.apache.felix.bundlerepository]]
==== *org.apache.felix.bundlerepository*
**Version**: 2.0.10

[source,xml]
----
<dependency>
    <groupId>org.apache.felix</groupId>
    <artifactId>org.apache.felix.bundlerepository</artifactId>
    <version>2.0.10</version>
</dependency>
----
[[org.apache.felix.bundlerepository]]
==== *org.apache.felix.bundlerepository*
**Version**: 2.0.10

[source,xml]
----
<dependency>
    <groupId>apache felix bundle repository</groupId>
    <artifactId>org.apache.felix.bundlerepository</artifactId>
    <version>2.0.10</version>
</dependency>
----
[[jakarta.json.bind-api]]
==== *jakarta.json.bind-api*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.json.bind</groupId>
    <artifactId>jakarta.json.bind-api</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[]]
==== **
**Version**: 0

[source,xml]
----
<dependency>
    <groupId>json-b api</groupId>
    <artifactId></artifactId>
    <version>0</version>
</dependency>
----
[[jakarta.interceptor-api]]
==== *jakarta.interceptor-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.interceptor</groupId>
    <artifactId>jakarta.interceptor-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[jakarta.interceptor-api]]
==== *jakarta.interceptor-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta interceptors</groupId>
    <artifactId>jakarta.interceptor-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[teams-notifier-console-plugin]]
==== *teams-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>teams-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.teams-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.teams-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>microsoft teams notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.teams-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.email-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.email-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>email notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.email-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[org.glassfish.tyrus.core]]
==== *org.glassfish.tyrus.core*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus core</groupId>
    <artifactId>org.glassfish.tyrus.core</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[console-plugin-service]]
==== *console-plugin-service*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admingui</groupId>
    <artifactId>console-plugin-service</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admingui.console-plugin-service]]
==== *fish.payara.server.core.admingui.console-plugin-service*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin console integration</groupId>
    <artifactId>fish.payara.server.core.admingui.console-plugin-service</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[snmp-notifier-core]]
==== *snmp-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>snmp-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.snmp-notifier-core]]
==== *fish.payara.extensions.notifiers.snmp-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>snmp notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.snmp-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[healthcheck-service-console-plugin]]
==== *healthcheck-service-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>healthcheck-service-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.healthcheck-service-console-plugin]]
==== *fish.payara.server.internal.admingui.healthcheck-service-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>healthcheck service console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.healthcheck-service-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[docker]]
==== *docker*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.docker</groupId>
    <artifactId>docker</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.docker]]
==== *fish.payara.server.internal.docker*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>docker</groupId>
    <artifactId>fish.payara.server.internal.docker</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[load-balancer-admin]]
==== *load-balancer-admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.load-balancer</groupId>
    <artifactId>load-balancer-admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.load-balancer.admin]]
==== *fish.payara.server.internal.load-balancer.admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>load-balancer admin</groupId>
    <artifactId>fish.payara.server.internal.load-balancer.admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[microprofile-opentracing]]
==== *microprofile-opentracing*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-opentracing</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[snakeyaml]]
==== *snakeyaml*
**Version**: 2.2

[source,xml]
----
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>2.2</version>
</dependency>
----
[[org.yaml.snakeyaml]]
==== *org.yaml.snakeyaml*
**Version**: 2.2.0

[source,xml]
----
<dependency>
    <groupId>snakeyaml</groupId>
    <artifactId>org.yaml.snakeyaml</artifactId>
    <version>2.2.0</version>
</dependency>
----
[[osgi-resource-locator]]
==== *osgi-resource-locator*
**Version**: 1.0.3

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>osgi-resource-locator</artifactId>
    <version>1.0.3</version>
</dependency>
----
[[org.glassfish.hk2.osgi-resource-locator]]
==== *org.glassfish.hk2.osgi-resource-locator*
**Version**: 1.0.3

[source,xml]
----
<dependency>
    <groupId>osgi resource locator</groupId>
    <artifactId>org.glassfish.hk2.osgi-resource-locator</artifactId>
    <version>1.0.3</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara micro cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.eclipse.angus.mail]]
==== *org.eclipse.angus.mail*
**Version**: 1.1.0

[source,xml]
----
<dependency>
    <groupId>angus mail provider</groupId>
    <artifactId>org.eclipse.angus.mail</artifactId>
    <version>1.1.0</version>
</dependency>
----
[[microprofile-connector]]
==== *microprofile-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[war-util]]
==== *war-util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>war-util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.war-util]]
==== *fish.payara.server.core.web.war-util*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>web container common utilities</groupId>
    <artifactId>fish.payara.server.core.web.war-util</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[web-naming]]
==== *web-naming*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-naming</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.web.jersey-mvc-connector]]
==== *fish.payara.server.internal.web.jersey-mvc-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jersey mvc tld connector implementation module</groupId>
    <artifactId>fish.payara.server.internal.web.jersey-mvc-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.web.naming]]
==== *fish.payara.server.core.web.naming*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>web container naming utilities</groupId>
    <artifactId>fish.payara.server.core.web.naming</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[web-sse]]
==== *web-sse*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-sse</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.sse]]
==== *fish.payara.server.core.web.sse*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>server-sent events</groupId>
    <artifactId>fish.payara.server.core.web.sse</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.web.jstl-connector]]
==== *fish.payara.server.internal.web.jstl-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jstl implementation connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jstl-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[eventbus-notifier-console-plugin]]
==== *eventbus-notifier-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>eventbus-notifier-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.eventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.eventbus-notifier-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.eventbus-notifier-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.deployment.transformer.deployment-transformer-api]]
==== *fish.payara.deployment.transformer.deployment-transformer-api*
**Version**: 1.3.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.deployment.transformer:deployment-transformer-api</groupId>
    <artifactId>fish.payara.deployment.transformer.deployment-transformer-api</artifactId>
    <version>1.3.0</version>
</dependency>
----
[[acc-config]]
==== *acc-config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>acc-config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.appclient.acc-config]]
==== *fish.payara.server.appclient.acc-config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>acc config classes (jaxb)</groupId>
    <artifactId>fish.payara.server.appclient.acc-config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[payara-micro-boot]]
==== *payara-micro-boot*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>payara-micro-boot</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.extras.payara-micro-boot]]
==== *fish.payara.server.internal.extras.payara-micro-boot*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara micro boot</groupId>
    <artifactId>fish.payara.server.internal.extras.payara-micro-boot</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[payara-micro-service]]
==== *payara-micro-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-service]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara micro service</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[hk2-extras]]
==== *hk2-extras*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-extras</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.extras]]
==== *org.glassfish.hk2.extras*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 extras module</groupId>
    <artifactId>org.glassfish.hk2.extras</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[payara-insight-console-plugin]]
==== *payara-insight-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>payara-insight-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.]]
==== *fish.payara.server.internal.admingui.*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara-insight-console-plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[config-api]]
==== *config-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>config-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.config-api]]
==== *fish.payara.server.core.admin.config-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-config-api</groupId>
    <artifactId>fish.payara.server.core.admin.config-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.eclipse.persistence.core]]
==== *org.eclipse.persistence.core*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink core</groupId>
    <artifactId>org.eclipse.persistence.core</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[com.sun.pkg.client]]
==== *com.sun.pkg.client*
**Version**: 1.0.0

[source,xml]
----
<dependency>
    <groupId>pkg-client</groupId>
    <artifactId>com.sun.pkg.client</artifactId>
    <version>1.0.0</version>
</dependency>
----
[[jakarta.enterprise.deploy-api]]
==== *jakarta.enterprise.deploy-api*
**Version**: 1.7.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.deploy</groupId>
    <artifactId>jakarta.enterprise.deploy-api</artifactId>
    <version>1.7.2</version>
</dependency>
----
[[healthcheck-metrics]]
==== *healthcheck-metrics*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>healthcheck-metrics</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[javax.enterprise.deploy-api]]
==== *javax.enterprise.deploy-api*
**Version**: 1.7.2

[source,xml]
----
<dependency>
    <groupId>javax.enterprise.deploy api</groupId>
    <artifactId>javax.enterprise.deploy-api</artifactId>
    <version>1.7.2</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.healthcheck-metrics]]
==== *fish.payara.server.internal.payara-appserver-modules.healthcheck-metrics*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>healthcheck metrics</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.healthcheck-metrics</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.eclipse.persistence.oracle]]
==== *org.eclipse.persistence.oracle*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink oracle extension</groupId>
    <artifactId>org.eclipse.persistence.oracle</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jakarta-xmlbind-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jakarta-xmlbind-annotations*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson module: jakarta xml bind annotations (jakarta.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc-jsp]]
==== *org.glassfish.jersey.ext.jersey-mvc-jsp*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc-jsp</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc-jsp</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[jakarta.mail-api]]
==== *jakarta.mail-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta mail api</groupId>
    <artifactId>jakarta.mail-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[jboss-classfilewriter]]
==== *jboss-classfilewriter*
**Version**: 1.3.0.final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.jboss.classfilewriter</groupId>
    <artifactId>jboss-classfilewriter</artifactId>
    <version>1.3.0.final.payara-p1</version>
</dependency>
----
[[teams-notifier-core]]
==== *teams-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>teams-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.teams-notifier-core]]
==== *fish.payara.extensions.notifiers.teams-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>microsoft teams notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.teams-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[jboss-]]
==== *jboss-*
**Version**: 1.3.0.finalpayara-p1

[source,xml]
----
<dependency>
    <groupId>classfilewriter</groupId>
    <artifactId>jboss-</artifactId>
    <version>1.3.0.finalpayara-p1</version>
</dependency>
----
[[org.eclipse.parsson.media]]
==== *org.eclipse.parsson.media*
**Version**: 1.1.5.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipse parsson media for jakarta restful web services</groupId>
    <artifactId>org.eclipse.parsson.media</artifactId>
    <version>1.1.5.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.inject.jersey-hk2]]
==== *org.glassfish.jersey.inject.jersey-hk2*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-inject-hk2</groupId>
    <artifactId>org.glassfish.jersey.inject.jersey-hk2</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[rest-monitoring-plugin]]
==== *rest-monitoring-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>rest-monitoring-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[kernel]]
==== *kernel*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.nucleus</groupId>
    <artifactId>kernel</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.nucleus.kernel]]
==== *fish.payara.server.core.nucleus.kernel*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>kernel classes</groupId>
    <artifactId>fish.payara.server.core.nucleus.kernel</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.jpa-container]]
==== *fish.payara.server.internal.persistence.jpa-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jpa container for glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.jpa-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[opentracing-repackaged]]
==== *opentracing-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>opentracing-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.packager.opentracing-repackaged]]
==== *fish.payara.server.core.packager.opentracing-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>repackaged opentracing</groupId>
    <artifactId>fish.payara.server.core.packager.opentracing-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.jmx-monitoring-plugin]]
==== *fish.payara.server.internal.admingui.jmx-monitoring-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jmx monitoring plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.jmx-monitoring-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[flashlight-extra-jdk-packages]]
==== *flashlight-extra-jdk-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.flashlight</groupId>
    <artifactId>flashlight-extra-jdk-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[pfl-basic-tools]]
==== *pfl-basic-tools*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-basic-tools</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[fish.payara.server.core.deployment.javaee-core]]
==== *fish.payara.server.core.deployment.javaee-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>deployment related javaee core classes</groupId>
    <artifactId>fish.payara.server.core.deployment.javaee-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.connectors.admin]]
==== *fish.payara.server.internal.connectors.admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connectors admin</groupId>
    <artifactId>fish.payara.server.internal.connectors.admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-ejb]]
==== *org.glassfish.tyrus.container-glassfish-ejb*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus ejb component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-ejb</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[payara-rest-endpoints]]
==== *payara-rest-endpoints*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-rest-endpoints</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-rest-endpoints]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-rest-endpoints*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>rest endpoints</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-rest-endpoints</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.connectors.internal-api]]
==== *fish.payara.server.core.connectors.internal-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>connectors private apis for glassfish containers</groupId>
    <artifactId>fish.payara.server.core.connectors.internal-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-client]]
==== *org.glassfish.jersey.core.jersey-client*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-client</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-client</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[aopalliance-repackaged]]
==== *aopalliance-repackaged*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2.external</groupId>
    <artifactId>aopalliance-repackaged</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.external.aopalliance-repackaged]]
==== *org.glassfish.hk2.external.aopalliance-repackaged*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>aopalliance version 1.0 repackaged as a module</groupId>
    <artifactId>org.glassfish.hk2.external.aopalliance-repackaged</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[fish.payara.server.internal.admingui.rest-monitoring-plugin]]
==== *fish.payara.server.internal.admingui.rest-monitoring-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>rest monitoring plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.rest-monitoring-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.pfl.pfl-basic-tools]]
==== *org.glassfish.pfl.pfl-basic-tools*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>pfl basic tools</groupId>
    <artifactId>org.glassfish.pfl.pfl-basic-tools</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.transaction.jta]]
==== *fish.payara.server.internal.transaction.jta*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jta implementation for glassfish</groupId>
    <artifactId>fish.payara.server.internal.transaction.jta</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.inject.jakarta.inject-api]]
==== *jakarta.inject.jakarta.inject-api*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta dependency injection</groupId>
    <artifactId>jakarta.inject.jakarta.inject-api</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[hk2-utils]]
==== *hk2-utils*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-utils</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.utils]]
==== *org.glassfish.hk2.utils*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 implementation utilities</groupId>
    <artifactId>org.glassfish.hk2.utils</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[orb-connector]]
==== *orb-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.orb</groupId>
    <artifactId>orb-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.orb.connector]]
==== *fish.payara.server.core.orb.connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish orb connector implementation</groupId>
    <artifactId>fish.payara.server.core.orb.connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.extensions.certificate-management.admin]]
==== *fish.payara.extensions.certificate-management.admin*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>payara certificate management admin commands</groupId>
    <artifactId>fish.payara.extensions.certificate-management.admin</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[security-connector-oidc-client]]
==== *security-connector-oidc-client*
**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>security connector - openid connect client</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>3.1.1</version>
</dependency>
----
[[fish.payara.server.internal.connectors.runtime]]
==== *fish.payara.server.internal.connectors.runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connectors runtime</groupId>
    <artifactId>fish.payara.server.internal.connectors.runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[snmp-notifier-console-plugin]]
==== *snmp-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>snmp-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.snmp-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.snmp-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>snmp notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.snmp-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.server.internal.webservices.connector]]
==== *fish.payara.server.internal.webservices.connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connector for glassfish web services container</groupId>
    <artifactId>fish.payara.server.internal.webservices.connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta standard tag library api</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[jsr107-repackaged]]
==== *jsr107-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>jsr107-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[pfl-tf]]
==== *pfl-tf*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-tf</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[org.glassfish.pfl.pfl-tf]]
==== *org.glassfish.pfl.pfl-tf*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>pfl tf</groupId>
    <artifactId>org.glassfish.pfl.pfl-tf</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.hibernate.validator]]
==== *org.hibernate.validator*
**Version**: 8.0.1.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator engine</groupId>
    <artifactId>org.hibernate.validator</artifactId>
    <version>8.0.1.final</version>
</dependency>
----
[[org.eclipse.persistence.jpa]]
==== *org.eclipse.persistence.jpa*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing]]
==== *fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara jax-rs client tracing</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[web-ha]]
==== *web-ha*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-ha</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-ejb-plugin]]
==== *fish.payara.server.internal.admingui.console-ejb-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console ejb container plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-ejb-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.web.ha]]
==== *fish.payara.server.internal.web.ha*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>web container ha code</groupId>
    <artifactId>fish.payara.server.internal.web.ha</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[metro-glue]]
==== *metro-glue*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>metro-glue</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.jsr107-repackaged]]
==== *fish.payara.server.internal.payara-modules.jsr107-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>repackaged jsr 107</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.jsr107-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-client]]
==== *fish.payara.server.internal.ejb.ejb-client*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish core ejb client</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-client</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta web services metadata api</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>3.0.0</version>
</dependency>
----
[[fish.payara.server.core.security.websecurity]]
==== *fish.payara.server.core.security.websecurity*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>webtier security integration</groupId>
    <artifactId>fish.payara.server.core.security.websecurity</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.packager.]]
==== *fish.payara.server.internal.packager.*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>metro-xmlsec-repackaged</groupId>
    <artifactId>fish.payara.server.internal.packager.</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-corba-csiv2-idl]]
==== *glassfish-corba-csiv2-idl*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-csiv2-idl</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[org.glassfish.corba.glassfish-corba-csiv2-idl]]
==== *org.glassfish.corba.glassfish-corba-csiv2-idl*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>generated csiv2 apis</groupId>
    <artifactId>org.glassfish.corba.glassfish-corba-csiv2-idl</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction api</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[org.eclipse.persistence.dbws]]
==== *org.eclipse.persistence.dbws*
**Version**: 4.0.1.payara-p2

[source,xml]
----
<dependency>
    <groupId>eclipselink dbws</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>4.0.1.payara-p2</version>
</dependency>
----
[[fish.payara.server.internal.deployment.admin]]
==== *fish.payara.server.internal.deployment.admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>deployment related admin classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.internal-api]]
==== *fish.payara.server.internal.persistence.cmp.internal-api*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>internal-api module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.internal-api</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.security.enterprise-api]]
==== *jakarta.security.enterprise-api*
**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta security</groupId>
    <artifactId>jakarta.security.enterprise-api</artifactId>
    <version>3.0.0</version>
</dependency>
----
[[fish.payara.server.internal.web.jsf-connector]]
==== *fish.payara.server.internal.web.jsf-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jsf implementation connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jsf-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[notification-eventbus-core]]
==== *notification-eventbus-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-eventbus-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-eventbus-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-eventbus-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[schema2beans]]
==== *schema2beans*
**Version**: 6.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>schema2beans</artifactId>
    <version>6.7</version>
</dependency>
----
[[org.glassfish.external.schema2beans]]
==== *org.glassfish.external.schema2beans*
**Version**: 6.7.0

[source,xml]
----
<dependency>
    <groupId>schema2beans repackaged as an osgi bundle</groupId>
    <artifactId>org.glassfish.external.schema2beans</artifactId>
    <version>6.7.0</version>
</dependency>
----
[[monitoring-console-core]]
==== *monitoring-console-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.monitoring-console</groupId>
    <artifactId>monitoring-console-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.monitoring-console.core]]
==== *fish.payara.server.internal.monitoring-console.core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>monitoring console core</groupId>
    <artifactId>fish.payara.server.internal.monitoring-console.core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.soteria.spi.bean.decorator.weld]]
==== *org.glassfish.soteria.spi.bean.decorator.weld*
**Version**: 3.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>soteria spi : bean decorator : weld</groupId>
    <artifactId>org.glassfish.soteria.spi.bean.decorator.weld</artifactId>
    <version>3.0.3.payara-p1</version>
</dependency>
----
[[resources-connector]]
==== *resources-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.resources</groupId>
    <artifactId>resources-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.resources.connector]]
==== *fish.payara.server.core.resources.connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>resources connector</groupId>
    <artifactId>fish.payara.server.core.resources.connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[slack-notifier-console-plugin]]
==== *slack-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>slack-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.slack-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.slack-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>slack notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.slack-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.server.internal.webservices.metro-glue]]
==== *fish.payara.server.internal.webservices.metro-glue*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish metro glue code</groupId>
    <artifactId>fish.payara.server.internal.webservices.metro-glue</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.concurrent.impl]]
==== *fish.payara.server.internal.concurrent.impl*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>concurrent implementation module</groupId>
    <artifactId>fish.payara.server.internal.concurrent.impl</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[osgi-adapter]]
==== *osgi-adapter*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>osgi-adapter</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.osgi-adapter]]
==== *org.glassfish.hk2.osgi-adapter*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 osgi adapter</groupId>
    <artifactId>org.glassfish.hk2.osgi-adapter</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[slack-notifier-core]]
==== *slack-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>slack-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.slack-notifier-core]]
==== *fish.payara.extensions.notifiers.slack-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>slack notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.slack-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jmx-monitoring]]
==== *fish.payara.server.internal.payara-appserver-modules.jmx-monitoring*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jmx monitoring</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jmx-monitoring</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[payara-jsr107]]
==== *payara-jsr107*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-jsr107</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-jsr107]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-jsr107*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara jsr107</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-jsr107</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-moxy</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[bcel]]
==== *bcel*
**Version**: 6.10.0

[source,xml]
----
<dependency>
    <groupId>org.apache.bcel</groupId>
    <artifactId>bcel</artifactId>
    <version>6.10.0</version>
</dependency>
----
[[org.apache.bcel]]
==== *org.apache.bcel*
**Version**: 6.10.0

[source,xml]
----
<dependency>
    <groupId>apache commons bcel</groupId>
    <artifactId>org.apache.bcel</artifactId>
    <version>6.10.0</version>
</dependency>
----
[[org.igniterealtime.smack.im]]
==== *org.igniterealtime.smack.im*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-im</groupId>
    <artifactId>org.igniterealtime.smack.im</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[faces-compat]]
==== *faces-compat*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admingui</groupId>
    <artifactId>faces-compat</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jakarta.faces]]
==== *jakarta.faces*
**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>3.0.2</version>
</dependency>
----
[[gmbal]]
==== *gmbal*
**Version**: 4.0.3

[source,xml]
----
<dependency>
    <groupId>org.glassfish.gmbal</groupId>
    <artifactId>gmbal</artifactId>
    <version>4.0.3</version>
</dependency>
----
[[org.glassfish.gmbal.gmbal]]
==== *org.glassfish.gmbal.gmbal*
**Version**: 4.0.3

[source,xml]
----
<dependency>
    <groupId>gmbal (implementation)</groupId>
    <artifactId>org.glassfish.gmbal.gmbal</artifactId>
    <version>4.0.3</version>
</dependency>
----
[[fish.payara.server.core.admingui.]]
==== *fish.payara.server.core.admingui.*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>faces-compat</groupId>
    <artifactId>fish.payara.server.core.admingui.</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[web-core]]
==== *web-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.core]]
==== *fish.payara.server.core.web.core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>core servlet container</groupId>
    <artifactId>fish.payara.server.core.web.core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[yasson]]
==== *yasson*
**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.4</version>
</dependency>
----
[[yasson]]
==== *yasson*
**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>yasson</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.4</version>
</dependency>
----
[[org.glassfish.jersey.ext.microprofile.]]
==== *org.glassfish.jersey.ext.microprofile.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-mp-rest-client</groupId>
    <artifactId>org.glassfish.jersey.ext.microprofile.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.extensions.certificate-management.common]]
==== *fish.payara.extensions.certificate-management.common*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>payara certificate management common</groupId>
    <artifactId>fish.payara.extensions.certificate-management.common</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[microprofile-console-plugin]]
==== *microprofile-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>microprofile-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[pfl-dynamic]]
==== *pfl-dynamic*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-dynamic</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.glassfish.pfl.pfl-dynamic]]
==== *org.glassfish.pfl.pfl-dynamic*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>pfl dynamic</groupId>
    <artifactId>org.glassfish.pfl.pfl-dynamic</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.concurrent.connector]]
==== *fish.payara.server.internal.concurrent.connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>concurrent connector module</groupId>
    <artifactId>fish.payara.server.internal.concurrent.connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[healthcheck-core]]
==== *healthcheck-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>healthcheck-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[hk2-locator]]
==== *hk2-locator*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-locator</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.healthcheck-core]]
==== *fish.payara.server.core.payara-modules.healthcheck-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>healthcheck core services</groupId>
    <artifactId>fish.payara.server.core.payara-modules.healthcheck-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.hk2.locator]]
==== *org.glassfish.hk2.locator*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>servicelocator default implementation</groupId>
    <artifactId>org.glassfish.hk2.locator</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[accessors-smart]]
==== *accessors-smart*
**Version**: 2.5.1

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>accessors-smart</artifactId>
    <version>2.5.1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-proxy-client]]
==== *org.glassfish.jersey.ext.jersey-proxy-client*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-proxy-client</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-proxy-client</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[net.minidev.]]
==== *net.minidev.*
**Version**: 2.5.1

[source,xml]
----
<dependency>
    <groupId>accessors-smart</groupId>
    <artifactId>net.minidev.</artifactId>
    <version>2.5.1</version>
</dependency>
----
[[console-common-full-plugin]]
==== *console-common-full-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-common-full-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-common-full-plugin]]
==== *fish.payara.server.internal.admingui.console-common-full-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console full distribution plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-common-full-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.tyrus.container-servlet]]
==== *org.glassfish.tyrus.container-servlet*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus servlet bundle</groupId>
    <artifactId>org.glassfish.tyrus.container-servlet</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta messaging api</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[fish.payara.server.core.deployment.deployment-client]]
==== *fish.payara.server.core.deployment.deployment-client*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>deployment client classes and interfaces</groupId>
    <artifactId>fish.payara.server.core.deployment.deployment-client</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[security-connector-oauth2-client]]
==== *security-connector-oauth2-client*
**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>security connector - oauth2 client</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>3.1.1</version>
</dependency>
----
[[jakarta.security.jacc-api]]
==== *jakarta.security.jacc-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta authorization</groupId>
    <artifactId>jakarta.security.jacc-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[rest-client]]
==== *rest-client*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>rest-client</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.rest-client]]
==== *fish.payara.server.core.admin.rest-client*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish admin rest client</groupId>
    <artifactId>fish.payara.server.core.admin.rest-client</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.security.ee]]
==== *fish.payara.server.core.security.ee*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>java ee security core classes</groupId>
    <artifactId>fish.payara.server.core.security.ee</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[newrelic-notifier-console-plugin]]
==== *newrelic-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>newrelic-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.newrelic-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.newrelic-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>new relic notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.newrelic-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[orb-iiop]]
==== *orb-iiop*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.orb</groupId>
    <artifactId>orb-iiop</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.orb.iiop]]
==== *fish.payara.server.internal.orb.iiop*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish orb interface layer implementation</groupId>
    <artifactId>fish.payara.server.internal.orb.iiop</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.connectors.gf-connectors-connector]]
==== *fish.payara.server.internal.connectors.gf-connectors-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish connectors connector</groupId>
    <artifactId>fish.payara.server.internal.connectors.gf-connectors-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[payara-console-extras]]
==== *payara-console-extras*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>payara-console-extras</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.payara-console-extras]]
==== *fish.payara.server.internal.admingui.payara-console-extras*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara console extras</groupId>
    <artifactId>fish.payara.server.internal.admingui.payara-console-extras</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[antlr-repackaged]]
==== *antlr-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>antlr-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.packager.antlr-repackaged]]
==== *fish.payara.server.internal.packager.antlr-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>antlr.all version 2.7.7 repackaged as a module</groupId>
    <artifactId>fish.payara.server.internal.packager.antlr-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.ejb.http-admin]]
==== *fish.payara.server.internal.ejb.http-admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ejb - http admin</groupId>
    <artifactId>fish.payara.server.internal.ejb.http-admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[config-types]]
==== *config-types*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.hk2</groupId>
    <artifactId>config-types</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.hk2.config-types]]
==== *fish.payara.server.core.hk2.config-types*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>hk2 config types</groupId>
    <artifactId>fish.payara.server.core.hk2.config-types</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[gf-admingui-connector]]
==== *gf-admingui-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admingui</groupId>
    <artifactId>gf-admingui-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admingui.gf-admingui-connector]]
==== *fish.payara.server.core.admingui.gf-admingui-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin console integration</groupId>
    <artifactId>fish.payara.server.core.admingui.gf-admingui-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[hk2-core]]
==== *hk2-core*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-core</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.core]]
==== *org.glassfish.hk2.core*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 core module</groupId>
    <artifactId>org.glassfish.hk2.core</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[logging]]
==== *logging*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.nucleus</groupId>
    <artifactId>logging</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.nucleus.logging]]
==== *fish.payara.server.core.nucleus.logging*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>nucleus logging classes</groupId>
    <artifactId>fish.payara.server.core.nucleus.logging</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-common]]
==== *org.glassfish.jersey.core.jersey-common*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-common</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-common</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[ssl-impl]]
==== *ssl-impl*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.security</groupId>
    <artifactId>ssl-impl</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.security.ssl-impl]]
==== *fish.payara.server.core.security.ssl-impl*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish ssl implementation module</groupId>
    <artifactId>fish.payara.server.core.security.ssl-impl</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.2

[source,xml]
----
<dependency>
    <groupId>stax2 api</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.2</version>
</dependency>
----
[[fish.payara.server.internal.web.gf-weld-connector]]
==== *fish.payara.server.internal.web.gf-weld-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>weld connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.gf-weld-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.faces]]
==== *jakarta.faces*
**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----
[[org.glassfish.jakarta.faces]]
==== *org.glassfish.jakarta.faces*
**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>mojarra faces implementation 4.0.7.payara-p1</groupId>
    <artifactId>org.glassfish.jakarta.faces</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.glassfish.]]
==== *org.glassfish.jersey.containers.glassfish.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-gf-ejb</groupId>
    <artifactId>org.glassfish.jersey.containers.glassfish.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.ejb.opentracing]]
==== *fish.payara.server.internal.ejb.opentracing*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ejb-opentracing</groupId>
    <artifactId>fish.payara.server.internal.ejb.opentracing</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jdbc-runtime]]
==== *jdbc-runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.jdbc.runtime]]
==== *fish.payara.server.internal.jdbc.runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jdbc runtime module</groupId>
    <artifactId>fish.payara.server.internal.jdbc.runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[simple-glassfish-api]]
==== *simple-glassfish-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>simple-glassfish-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.simple-glassfish-api]]
==== *fish.payara.server.core.common.simple-glassfish-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>simple public apis of glassfish</groupId>
    <artifactId>fish.payara.server.core.common.simple-glassfish-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[cluster-admin]]
==== *cluster-admin*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.cluster</groupId>
    <artifactId>cluster-admin</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.cluster.admin]]
==== *fish.payara.server.core.cluster.admin*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>cluster-admin</groupId>
    <artifactId>fish.payara.server.core.cluster.admin</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.security]]
==== *fish.payara.server.core.security*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>security core classes</groupId>
    <artifactId>fish.payara.server.core.security</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[environment-warning]]
==== *environment-warning*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>environment-warning</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.environment-warning]]
==== *fish.payara.server.internal.payara-appserver-modules.environment-warning*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>environment warning</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.environment-warning</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-server]]
==== *org.glassfish.jersey.core.jersey-server*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-server</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-server</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[console-reference-manual-plugin]]
==== *console-reference-manual-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-reference-manual-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-reference-manual-plugin]]
==== *fish.payara.server.internal.admingui.console-reference-manual-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console reference manual plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-reference-manual-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 8.0.1.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>8.0.1.final</version>
</dependency>
----
[[org.igniterealtime.smack.java7]]
==== *org.igniterealtime.smack.java7*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-java7</groupId>
    <artifactId>org.igniterealtime.smack.java7</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[org.osgi.service.component]]
==== *org.osgi.service.component*
**Version**: 1.5.1

[source,xml]
----
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.service.component</artifactId>
    <version>1.5.1</version>
</dependency>
----
[[org.osgi.service.component]]
==== *org.osgi.service.component*
**Version**: 1.5.1.202212101352

[source,xml]
----
<dependency>
    <groupId>org.osgi:org.osgi.service.component</groupId>
    <artifactId>org.osgi.service.component</artifactId>
    <version>1.5.1.202212101352</version>
</dependency>
----
[[fish.payara.server.core.deployment.common]]
==== *fish.payara.server.core.deployment.common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>deployment related common classes</groupId>
    <artifactId>fish.payara.server.core.deployment.common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-annotations]]
==== *com.fasterxml.jackson.core.jackson-annotations*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson-annotations</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-annotations</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer]]
==== *fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>hz ejb timer</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-mbeanserver]]
==== *glassfish-mbeanserver*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>glassfish-mbeanserver</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.glassfish-mbeanserver]]
==== *fish.payara.server.core.common.glassfish-mbeanserver*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish mbeanserver support</groupId>
    <artifactId>fish.payara.server.core.common.glassfish-mbeanserver</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[monitoring-console-process]]
==== *monitoring-console-process*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.monitoring-console</groupId>
    <artifactId>monitoring-console-process</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[fish.payara.monitoring-console.process]]
==== *fish.payara.monitoring-console.process*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>monitoring-console-process</groupId>
    <artifactId>fish.payara.monitoring-console.process</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[j-interop-repackaged]]
==== *j-interop-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>j-interop-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.packager.j-interop-repackaged]]
==== *fish.payara.server.core.packager.j-interop-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>j-interop repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.j-interop-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[healthcheck-checker]]
==== *healthcheck-checker*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>healthcheck-checker</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.metro.webservices-osgi]]
==== *org.glassfish.metro.webservices-osgi*
**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>metro web services runtime osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-osgi</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.healthcheck-checker]]
==== *fish.payara.server.internal.payara-appserver-modules.healthcheck-checker*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>healthcheck checker</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.healthcheck-checker</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[grizzly-npn-osgi]]
==== *grizzly-npn-osgi*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-npn-osgi</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[org.glassfish.grizzly.npn-osgi]]
==== *org.glassfish.grizzly.npn-osgi*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>grizzly-npn-osgi</groupId>
    <artifactId>org.glassfish.grizzly.npn-osgi</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[org.osgi.util.function]]
==== *org.osgi.util.function*
**Version**: 1.2.0

[source,xml]
----
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.util.function</artifactId>
    <version>1.2.0</version>
</dependency>
----
[[org.osgi.util.function]]
==== *org.osgi.util.function*
**Version**: 1.2.0.202109301733

[source,xml]
----
<dependency>
    <groupId>org.osgi:org.osgi.util.function</groupId>
    <artifactId>org.osgi.util.function</artifactId>
    <version>1.2.0.202109301733</version>
</dependency>
----
[[jakarta.websocket-api]]
==== *jakarta.websocket-api*
**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta websocket - server api</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>2.1.1</version>
</dependency>
----
[[notification-core]]
==== *notification-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-core]]
==== *fish.payara.server.internal.payara-modules.notification-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>notification core services</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-grizzly-extra-all]]
==== *glassfish-grizzly-extra-all*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.grizzly</groupId>
    <artifactId>glassfish-grizzly-extra-all</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.grizzly.glassfish-grizzly-extra-all]]
==== *fish.payara.server.internal.grizzly.glassfish-grizzly-extra-all*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish grizzly extra jars combining</groupId>
    <artifactId>fish.payara.server.internal.grizzly.glassfish-grizzly-extra-all</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[rest-client-ssl]]
==== *rest-client-ssl*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>rest-client-ssl</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[resources-runtime]]
==== *resources-runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.rest-client-ssl]]
==== *fish.payara.server.internal.payara-appserver-modules.rest-client-ssl*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>rest client ssl context</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.rest-client-ssl</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.client]]
==== *org.glassfish.tyrus.client*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus client</groupId>
    <artifactId>org.glassfish.tyrus.client</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.server]]
==== *org.glassfish.tyrus.server*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus server</groupId>
    <artifactId>org.glassfish.tyrus.server</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.resources.runtime]]
==== *fish.payara.server.internal.resources.runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish resources runtime</groupId>
    <artifactId>fish.payara.server.internal.resources.runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[requesttracing-core]]
==== *requesttracing-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>requesttracing-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.requesttracing-core]]
==== *fish.payara.server.core.payara-modules.requesttracing-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>request tracing core services</groupId>
    <artifactId>fish.payara.server.core.payara-modules.requesttracing-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-ejb]]
==== *fish.payara.server.internal.persistence.cmp.support-ejb*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>support ejb module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-ejb</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[gf-restadmin-connector]]
==== *gf-restadmin-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>gf-restadmin-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admin.gf-restadmin-connector]]
==== *fish.payara.server.internal.admin.gf-restadmin-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>connector for glassfish admin rest service</groupId>
    <artifactId>fish.payara.server.internal.admin.gf-restadmin-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[cluster-common]]
==== *cluster-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.cluster</groupId>
    <artifactId>cluster-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.cluster.common]]
==== *fish.payara.server.core.cluster.common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>cluster-common</groupId>
    <artifactId>fish.payara.server.core.cluster.common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[console-web-plugin]]
==== *console-web-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-web-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-web-plugin]]
==== *fish.payara.server.internal.admingui.console-web-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console web container plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-web-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[classmate]]
==== *classmate*
**Version**: 1.7.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml</groupId>
    <artifactId>classmate</artifactId>
    <version>1.7.0</version>
</dependency>
----
[[nucleus-grizzly-all]]
==== *nucleus-grizzly-all*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.grizzly</groupId>
    <artifactId>nucleus-grizzly-all</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[admin-cli]]
==== *admin-cli*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>admin-cli</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.cli]]
==== *fish.payara.server.core.admin.cli*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-cli</groupId>
    <artifactId>fish.payara.server.core.admin.cli</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jakarta.json-api]]
==== *jakarta.json-api*
**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.json</groupId>
    <artifactId>jakarta.json-api</artifactId>
    <version>2.1.0</version>
</dependency>
----
[[parsson]]
==== *parsson*
**Version**: 1.1.5.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>parsson</artifactId>
    <version>1.1.5.payara-p1</version>
</dependency>
----
[[jakarta.json]]
==== *jakarta.json*
**Version**: 1.1.5.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>jakarta.json</artifactId>
    <version>1.1.5.payara-p1</version>
</dependency>
----
[[fish.payara.server.core.grizzly.nucleus-grizzly-all]]
==== *fish.payara.server.core.grizzly.nucleus-grizzly-all*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>nucleus grizzly jars combining</groupId>
    <artifactId>fish.payara.server.core.grizzly.nucleus-grizzly-all</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.eclipse.parsson.jakarta.json]]
==== *org.eclipse.parsson.jakarta.json*
**Version**: 1.1.5.payara-p1

[source,xml]
----
<dependency>
    <groupId>json-p with parsson provider</groupId>
    <artifactId>org.eclipse.parsson.jakarta.json</artifactId>
    <version>1.1.5.payara-p1</version>
</dependency>
----
[[datadog-notifier-core]]
==== *datadog-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>datadog-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[pfl-basic]]
==== *pfl-basic*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-basic</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.glassfish.pfl.pfl-basic]]
==== *org.glassfish.pfl.pfl-basic*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>pfl basic</groupId>
    <artifactId>org.glassfish.pfl.pfl-basic</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[fish.payara.extensions.notifiers.datadog-notifier-core]]
==== *fish.payara.extensions.notifiers.datadog-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>datadog notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.datadog-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[jakarta.enterprise.concurrent-api]]
==== *jakarta.enterprise.concurrent-api*
**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta concurrency</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>3.0.4</version>
</dependency>
----
[[gf-load-balancer-connector]]
==== *gf-load-balancer-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.load-balancer</groupId>
    <artifactId>gf-load-balancer-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.load-balancer.gf-load-balancer-connector]]
==== *fish.payara.server.internal.load-balancer.gf-load-balancer-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>load balancer internal api</groupId>
    <artifactId>fish.payara.server.internal.load-balancer.gf-load-balancer-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[appclient-server-core]]
==== *appclient-server-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.appclient.server</groupId>
    <artifactId>appclient-server-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.appclient.server.appclient-server-core]]
==== *fish.payara.server.internal.appclient.server.appclient-server-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish appclient server-side core</groupId>
    <artifactId>fish.payara.server.internal.appclient.server.appclient-server-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jsr109-impl]]
==== *jsr109-impl*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>jsr109-impl</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.webservices.jsr109-impl]]
==== *fish.payara.server.internal.webservices.jsr109-impl*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jsr-109 implementation to deploy metro</groupId>
    <artifactId>fish.payara.server.internal.webservices.jsr109-impl</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[nucleus-resources]]
==== *nucleus-resources*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.resourcebase.resources</groupId>
    <artifactId>nucleus-resources</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[io.projectreactor.]]
==== *io.projectreactor.*
**Version**: 3.6.9.release

[source,xml]
----
<dependency>
    <groupId>reactor-core</groupId>
    <artifactId>io.projectreactor.</artifactId>
    <version>3.6.9.release</version>
</dependency>
----
[[fish.payara.server.core.resourcebase.resources.]]
==== *fish.payara.server.core.resourcebase.resources.*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>nucleus.resources</groupId>
    <artifactId>fish.payara.server.core.resourcebase.resources.</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-bean-validation]]
==== *org.glassfish.jersey.ext.jersey-bean-validation*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-bean-validation</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-bean-validation</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[istack-commons-runtime]]
==== *istack-commons-runtime*
**Version**: 4.2.0

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>4.2.0</version>
</dependency>
----
[[com.sun.istack.commons-runtime]]
==== *com.sun.istack.commons-runtime*
**Version**: 4.2.0

[source,xml]
----
<dependency>
    <groupId>istack common utility code runtime</groupId>
    <artifactId>com.sun.istack.commons-runtime</artifactId>
    <version>4.2.0</version>
</dependency>
----
[[fish.payara.deployment.transformer.deployment-transformer-impl]]
==== *fish.payara.deployment.transformer.deployment-transformer-impl*
**Version**: 1.3.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.deployment.transformer:deployment-transformer-impl</groupId>
    <artifactId>fish.payara.deployment.transformer.deployment-transformer-impl</artifactId>
    <version>1.3.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.resources.javamail-runtime]]
==== *fish.payara.server.internal.resources.javamail-runtime*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish javamail runtime</groupId>
    <artifactId>fish.payara.server.internal.resources.javamail-runtime</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.connectors.work-management]]
==== *fish.payara.server.internal.connectors.work-management*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>work management</groupId>
    <artifactId>fish.payara.server.internal.connectors.work-management</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta enterprise beans api</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[wasp]]
==== *wasp*
**Version**: 3.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.wasp</groupId>
    <artifactId>wasp</artifactId>
    <version>3.2.2</version>
</dependency>
----
[[console-jca-plugin]]
==== *console-jca-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jca-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-jca-plugin]]
==== *fish.payara.server.internal.admingui.console-jca-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console connectors plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-jca-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta-ee9-shim]]
==== *jakarta-ee9-shim*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jakarta-ee9-shim</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.packager.]]
==== *fish.payara.server.internal.packager.*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jakarta-ee9-shim</groupId>
    <artifactId>fish.payara.server.internal.packager.</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.wasp.wasp]]
==== *org.glassfish.wasp.wasp*
**Version**: 3.2.2

[source,xml]
----
<dependency>
    <groupId>wasp jakarta server pages implementation 3.2.2</groupId>
    <artifactId>org.glassfish.wasp.wasp</artifactId>
    <version>3.2.2</version>
</dependency>
----
[[healthcheck-cpool]]
==== *healthcheck-cpool*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>healthcheck-cpool</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 4.0.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta xml binding api</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.1.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.healthcheck-cpool]]
==== *fish.payara.server.internal.payara-modules.healthcheck-cpool*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>healthcheck connection pool</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.healthcheck-cpool</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[phonehome-bootstrap]]
==== *phonehome-bootstrap*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>phonehome-bootstrap</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.phonehome-bootstrap]]
==== *fish.payara.server.internal.payara-modules.phonehome-bootstrap*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara phonehome bootstrap</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.phonehome-bootstrap</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.web.jspcaching-connector]]
==== *fish.payara.server.internal.web.jspcaching-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jsp caching taglib connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jspcaching-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[xmpp-notifier-console-plugin]]
==== *xmpp-notifier-console-plugin*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>xmpp-notifier-console-plugin</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.xmpp-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.xmpp-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>xmpp notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.xmpp-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[dol]]
==== *dol*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.deployment</groupId>
    <artifactId>dol</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[container-common]]
==== *container-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>container-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[com.fasterxml.classmate]]
==== *com.fasterxml.classmate*
**Version**: 1.7.0

[source,xml]
----
<dependency>
    <groupId>classmate</groupId>
    <artifactId>com.fasterxml.classmate</artifactId>
    <version>1.7.0</version>
</dependency>
----
[[fish.payara.server.core.common.container-common]]
==== *fish.payara.server.core.common.container-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>container common</groupId>
    <artifactId>fish.payara.server.core.common.container-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[osgi-cli-remote]]
==== *osgi-cli-remote*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.osgi-platforms</groupId>
    <artifactId>osgi-cli-remote</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.osgi-platforms.osgi-cli-remote]]
==== *fish.payara.server.internal.osgi-platforms.osgi-cli-remote*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin cli bridge command to the osgi shell</groupId>
    <artifactId>fish.payara.server.internal.osgi-platforms.osgi-cli-remote</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[realm-stores]]
==== *realm-stores*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>realm-stores</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-core]]
==== *com.fasterxml.jackson.core.jackson-core*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson-core</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-core</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[fish.payara.server.internal.security.realm-stores]]
==== *fish.payara.server.internal.security.realm-stores*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>realm identity stores</groupId>
    <artifactId>fish.payara.server.internal.security.realm-stores</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[pfl-tf-tools]]
==== *pfl-tf-tools*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-tf-tools</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[org.glassfish.pfl.pfl-tf-tools]]
==== *org.glassfish.pfl.pfl-tf-tools*
**Version**: 4.1.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>pfl tf tools</groupId>
    <artifactId>org.glassfish.pfl.pfl-tf-tools</artifactId>
    <version>4.1.2.payara-p1</version>
</dependency>
----
[[jts]]
==== *jts*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jts</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.transaction.jts]]
==== *fish.payara.server.internal.transaction.jts*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jts implementation for glassfish</groupId>
    <artifactId>fish.payara.server.internal.transaction.jts</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-sse</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[org.jxmpp.core]]
==== *org.jxmpp.core*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-core</groupId>
    <artifactId>org.jxmpp.core</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[jdbc-config]]
==== *jdbc-config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.jdbc.config]]
==== *fish.payara.server.internal.jdbc.config*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jdbc config module</groupId>
    <artifactId>fish.payara.server.internal.jdbc.config</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[console-common]]
==== *console-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admingui</groupId>
    <artifactId>console-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.security.services]]
==== *fish.payara.server.core.security.services*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>security services and spi</groupId>
    <artifactId>fish.payara.server.core.security.services</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[console-jdbc-plugin]]
==== *console-jdbc-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jdbc-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-jdbc-plugin]]
==== *fish.payara.server.internal.admingui.console-jdbc-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console jdbc plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-jdbc-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta annotations api</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>2.1.1</version>
</dependency>
----
[[fish.payara.server.internal.deployment.autodeploy]]
==== *fish.payara.server.internal.deployment.autodeploy*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>autodeploy classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.autodeploy</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[trilead-ssh2-repackaged]]
==== *trilead-ssh2-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>trilead-ssh2-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[eddsa]]
==== *eddsa*
**Version**: 0.3.0

[source,xml]
----
<dependency>
    <groupId>net.i2p.crypto</groupId>
    <artifactId>eddsa</artifactId>
    <version>0.3.0</version>
</dependency>
----
[[trilead-ssh2]]
==== *trilead-ssh2*
**Version**: build-217-jenkins-16

[source,xml]
----
<dependency>
    <groupId>org.jenkins-ci</groupId>
    <artifactId>trilead-ssh2</artifactId>
    <version>build-217-jenkins-16</version>
</dependency>
----
[[fish.payara.server.core.packager.trilead-ssh2-repackaged]]
==== *fish.payara.server.core.packager.trilead-ssh2-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>trilead-ssh2 repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.trilead-ssh2-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.deployment.dol]]
==== *fish.payara.server.core.deployment.dol*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>deployment object library</groupId>
    <artifactId>fish.payara.server.core.deployment.dol</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[ant]]
==== *ant*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>ant</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.packager.ant]]
==== *fish.payara.server.internal.packager.ant*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ant repackaging</groupId>
    <artifactId>fish.payara.server.internal.packager.ant</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.extensions.notifiers.discord-notifier-core]]
==== *fish.payara.extensions.notifiers.discord-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>discord notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.discord-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[hk2-config]]
==== *hk2-config*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.hk2</groupId>
    <artifactId>hk2-config</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.hk2.config]]
==== *fish.payara.server.core.hk2.config*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>hk2 configuration module</groupId>
    <artifactId>fish.payara.server.core.hk2.config</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[com.sun.xml.bind.jaxb-osgi]]
==== *com.sun.xml.bind.jaxb-osgi*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jaxb osgi</groupId>
    <artifactId>com.sun.xml.bind.jaxb-osgi</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[admin-core]]
==== *admin-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>admin-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.core]]
==== *fish.payara.server.core.admin.core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-core</groupId>
    <artifactId>fish.payara.server.core.admin.core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[amx-core]]
==== *amx-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>amx-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.amx-core]]
==== *fish.payara.server.core.common.amx-core*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>amx core</groupId>
    <artifactId>fish.payara.server.core.common.amx-core</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[hk2-api]]
==== *hk2-api*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-api</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.api]]
==== *org.glassfish.hk2.api*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 api module</groupId>
    <artifactId>org.glassfish.hk2.api</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[jakartaee-kernel]]
==== *jakartaee-kernel*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>jakartaee-kernel</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.core.jakartaee-kernel]]
==== *fish.payara.server.internal.core.jakartaee-kernel*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jakarta ee related distributions kernel classes</groupId>
    <artifactId>fish.payara.server.internal.core.jakartaee-kernel</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.minidns.core]]
==== *org.minidns.core*
**Version**: 0.3.4

[source,xml]
----
<dependency>
    <groupId>minidns-core</groupId>
    <artifactId>org.minidns.core</artifactId>
    <version>0.3.4</version>
</dependency>
----
[[launcher]]
==== *launcher*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.admin</groupId>
    <artifactId>launcher</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.admin.launcher]]
==== *fish.payara.server.core.admin.launcher*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin-launcher</groupId>
    <artifactId>fish.payara.server.core.admin.launcher</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[web-gui-plugin-common]]
==== *web-gui-plugin-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-gui-plugin-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.gui-plugin-common]]
==== *fish.payara.server.core.web.gui-plugin-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>web container and gui plug-in common classes</groupId>
    <artifactId>fish.payara.server.core.web.gui-plugin-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[rest-service]]
==== *rest-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>rest-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admin.rest-service]]
==== *fish.payara.server.internal.admin.rest-service*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish admin rest service</groupId>
    <artifactId>fish.payara.server.internal.admin.rest-service</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.admingui.console-common]]
==== *fish.payara.server.core.admingui.console-common*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>admin console common</groupId>
    <artifactId>fish.payara.server.core.admingui.console-common</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.ejb.gf-ejb-connector]]
==== *fish.payara.server.internal.ejb.gf-ejb-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ejb container connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.ejb.gf-ejb-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jaspic.provider.framework]]
==== *jaspic.provider.framework*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.security</groupId>
    <artifactId>jaspic.provider.framework</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.security.jaspic.provider.framework]]
==== *fish.payara.server.core.security.jaspic.provider.framework*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>jaspic provider framework</groupId>
    <artifactId>fish.payara.server.core.security.jaspic.provider.framework</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.security.webservices.security]]
==== *fish.payara.server.internal.security.webservices.security*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>webservices security and jsr 196 implementation</groupId>
    <artifactId>fish.payara.server.internal.security.webservices.security</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.security.connectors.security-connectors-api]]
==== *fish.payara.security.connectors.security-connectors-api*
**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>payara security connnectors api</groupId>
    <artifactId>fish.payara.security.connectors.security-connectors-api</artifactId>
    <version>3.1.1</version>
</dependency>
----
[[gf-web-connector]]
==== *gf-web-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>gf-web-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.gf-web-connector]]
==== *fish.payara.server.core.web.gf-web-connector*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>connector for glassfish web container</groupId>
    <artifactId>fish.payara.server.core.web.gf-web-connector</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles]]
==== *fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>cdi auth: roles</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.tyrus.spi]]
==== *org.glassfish.tyrus.spi*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus container spi</groupId>
    <artifactId>org.glassfish.tyrus.spi</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[fish.payara.extensions.notifiers.discord-notifier-console-plugin]]
==== *fish.payara.extensions.notifiers.discord-notifier-console-plugin*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>discord notifier console plugin</groupId>
    <artifactId>fish.payara.extensions.notifiers.discord-notifier-console-plugin</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[healthcheck-stuck]]
==== *healthcheck-stuck*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>healthcheck-stuck</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.metro.webservices-extra-jdk-packages]]
==== *org.glassfish.metro.webservices-extra-jdk-packages*
**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>extra jdk packages required by metro web services osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-extra-jdk-packages</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.healthcheck-stuck]]
==== *fish.payara.server.core.payara-modules.healthcheck-stuck*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>healthcheck stuck threads</groupId>
    <artifactId>fish.payara.server.core.payara-modules.healthcheck-stuck</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-entity-filtering]]
==== *org.glassfish.jersey.ext.jersey-entity-filtering*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-entity-filtering</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-entity-filtering</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.security.ejb.security]]
==== *fish.payara.server.internal.security.ejb.security*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ejb security integration</groupId>
    <artifactId>fish.payara.server.internal.security.ejb.security</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.igniterealtime.smack.core]]
==== *org.igniterealtime.smack.core*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-core</groupId>
    <artifactId>org.igniterealtime.smack.core</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[opentelemetry-repackaged]]
==== *opentelemetry-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>opentelemetry-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jctools-core]]
==== *jctools-core*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.jctools</groupId>
    <artifactId>jctools-core</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[jakarta.el-api]]
==== *jakarta.el-api*
**Version**: 5.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta expression language api</groupId>
    <artifactId>jakarta.el-api</artifactId>
    <version>5.0.1</version>
</dependency>
----
[[javassist]]
==== *javassist*
**Version**: 3.30.2-ga

[source,xml]
----
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.30.2-ga</version>
</dependency>
----
[[javassist]]
==== *javassist*
**Version**: 3.30.2.ga

[source,xml]
----
<dependency>
    <groupId>javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.30.2.ga</version>
</dependency>
----
[[fish.payara.server.core.packager.opentelemetry-repackaged]]
==== *fish.payara.server.core.packager.opentelemetry-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>repackaged opentelemetry</groupId>
    <artifactId>fish.payara.server.core.packager.opentelemetry-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[api-exporter]]
==== *api-exporter*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.nucleus</groupId>
    <artifactId>api-exporter</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[glassfish-application-common-module]]
==== *glassfish-application-common-module*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish api exporter module</groupId>
    <artifactId>glassfish-application-common-module</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[ha-api]]
==== *ha-api*
**Version**: 3.1.13

[source,xml]
----
<dependency>
    <groupId>org.glassfish.ha</groupId>
    <artifactId>ha-api</artifactId>
    <version>3.1.13</version>
</dependency>
----
[[org.glassfish.ha.ha-api]]
==== *org.glassfish.ha.ha-api*
**Version**: 3.1.13

[source,xml]
----
<dependency>
    <groupId>glassfish high availability apis and spi</groupId>
    <artifactId>org.glassfish.ha.ha-api</artifactId>
    <version>3.1.13</version>
</dependency>
----
[[woodstox-core]]
==== *woodstox-core*
**Version**: 6.6.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
    <version>6.6.2</version>
</dependency>
----
[[xsdlib]]
==== *xsdlib*
**Version**: 2022.7

[source,xml]
----
<dependency>
    <groupId>net.java.dev.msv</groupId>
    <artifactId>xsdlib</artifactId>
    <version>2022.7</version>
</dependency>
----
[[isorelax]]
==== *isorelax*
**Version**: 20090621

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.jaxb</groupId>
    <artifactId>isorelax</artifactId>
    <version>20090621</version>
</dependency>
----
[[com.fasterxml.woodstox.woodstox-core]]
==== *com.fasterxml.woodstox.woodstox-core*
**Version**: 6.6.2

[source,xml]
----
<dependency>
    <groupId>woodstox</groupId>
    <artifactId>com.fasterxml.woodstox.woodstox-core</artifactId>
    <version>6.6.2</version>
</dependency>
----
[[fish.payara.server.core.transaction.internal-api]]
==== *fish.payara.server.core.transaction.internal-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>transaction service internal api</groupId>
    <artifactId>fish.payara.server.core.transaction.internal-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[snmp4j-repackaged]]
==== *snmp4j-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>snmp4j-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[snmp4j]]
==== *snmp4j*
**Version**: 2.5.3

[source,xml]
----
<dependency>
    <groupId>org.snmp4j</groupId>
    <artifactId>snmp4j</artifactId>
    <version>2.5.3</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-payara-enterprise-branding-plugin]]
==== *fish.payara.server.internal.admingui.console-payara-enterprise-branding-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console payara enterprise theme plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-payara-enterprise-branding-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.packager.snmp4j-repackaged]]
==== *fish.payara.server.core.packager.snmp4j-repackaged*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>snmp4j repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.snmp4j-repackaged</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>cdi event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination]]
==== *fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>hz eclipselink coordination</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[web-cli]]
==== *web-cli*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-cli</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.cli]]
==== *fish.payara.server.core.web.cli*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>web module command line interface</groupId>
    <artifactId>fish.payara.server.core.web.cli</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[asadmin-recorder]]
==== *asadmin-recorder*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>asadmin-recorder</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-corba-omgapi]]
==== *glassfish-corba-omgapi*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-omgapi</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.asadmin-recorder]]
==== *fish.payara.server.internal.payara-modules.asadmin-recorder*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>payara asadmin recorder</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.asadmin-recorder</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[reactive-streams]]
==== *reactive-streams*
**Version**: 1.0.4

[source,xml]
----
<dependency>
    <groupId>reactive-streams-jvm</groupId>
    <artifactId>reactive-streams</artifactId>
    <version>1.0.4</version>
</dependency>
----
[[org.glassfish.corba.glassfish-corba-omgapi]]
==== *org.glassfish.corba.glassfish-corba-omgapi*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>generated omg apis</groupId>
    <artifactId>org.glassfish.corba.glassfish-corba-omgapi</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[org.glassfish.exousia]]
==== *org.glassfish.exousia*
**Version**: 2.1.2

[source,xml]
----
<dependency>
    <groupId>exousia jakarta authorization implementation 2.1.2</groupId>
    <artifactId>org.glassfish.exousia</artifactId>
    <version>2.1.2</version>
</dependency>
----
[[scattered-archive-api]]
==== *scattered-archive-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>scattered-archive-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.resources.javamail-connector]]
==== *fish.payara.server.internal.resources.javamail-connector*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>javamail connector</groupId>
    <artifactId>fish.payara.server.internal.resources.javamail-connector</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.common.scattered-archive-api]]
==== *fish.payara.server.core.common.scattered-archive-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>scattered archive apis of glassfish</groupId>
    <artifactId>fish.payara.server.core.common.scattered-archive-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[tiger-types]]
==== *tiger-types*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>tiger-types</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.packager.tiger-types]]
==== *fish.payara.server.core.packager.tiger-types*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>repackaged tiger-types</groupId>
    <artifactId>fish.payara.server.core.packager.tiger-types</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jakarta.validation.jakarta.validation-api]]
==== *jakarta.validation.jakarta.validation-api*
**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta bean validation api</groupId>
    <artifactId>jakarta.validation.jakarta.validation-api</artifactId>
    <version>3.0.2</version>
</dependency>
----
[[glassfish-corba-internal-api]]
==== *glassfish-corba-internal-api*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-internal-api</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[org.glassfish.jakarta.security.enterprise]]
==== *org.glassfish.jakarta.security.enterprise*
**Version**: 3.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>soteria jakarta security implementation 3.0.3.payara-p1</groupId>
    <artifactId>org.glassfish.jakarta.security.enterprise</artifactId>
    <version>3.0.3.payara-p1</version>
</dependency>
----
[[org.glassfish.corba.glassfish-corba-internal-api]]
==== *org.glassfish.corba.glassfish-corba-internal-api*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>exposed internal apis</groupId>
    <artifactId>org.glassfish.corba.glassfish-corba-internal-api</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[rmic]]
==== *rmic*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>rmic</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[org.glassfish.corba.rmic]]
==== *org.glassfish.corba.rmic*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>rmic compiler</groupId>
    <artifactId>org.glassfish.corba.rmic</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-yaml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-yaml*
**Version**: 2.17.2

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-yaml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-yaml</artifactId>
    <version>2.17.2</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-ejb-lite-plugin]]
==== *fish.payara.server.internal.admingui.console-ejb-lite-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console ejb local (lite) plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-ejb-lite-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-extra-jre-packages]]
==== *glassfish-extra-jre-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>glassfish-extra-jre-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.servlet.jsp-api]]
==== *jakarta.servlet.jsp-api*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta server pages api</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[fish.payara.server.internal.core.glassfish-extra-jre-packages]]
==== *fish.payara.server.internal.core.glassfish-extra-jre-packages*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish extra jre packages</groupId>
    <artifactId>fish.payara.server.internal.core.glassfish-extra-jre-packages</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.core.ejb.internal-api]]
==== *fish.payara.server.core.ejb.internal-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>ejb container internal api</groupId>
    <artifactId>fish.payara.server.core.ejb.internal-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[payara-api]]
==== *payara-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.api</groupId>
    <artifactId>payara-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-container]]
==== *fish.payara.server.internal.ejb.ejb-container*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>glassfish core ejb container implementation</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-container</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[backup]]
==== *backup*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>backup</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admin.backup]]
==== *fish.payara.server.internal.admin.backup*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>backup restore classes</groupId>
    <artifactId>fish.payara.server.internal.admin.backup</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[glassfish-corba-orb]]
==== *glassfish-corba-orb*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-orb</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[org.glassfish.corba.glassfish-corba-orb]]
==== *org.glassfish.corba.glassfish-corba-orb*
**Version**: 4.2.4.payara-p2

[source,xml]
----
<dependency>
    <groupId>glassfish corba orb</groupId>
    <artifactId>org.glassfish.corba.glassfish-corba-orb</artifactId>
    <version>4.2.4.payara-p2</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.enhancer]]
==== *fish.payara.server.internal.persistence.cmp.enhancer*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>enhancer module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.enhancer</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.notification-jms-core]]
==== *fish.payara.server.internal.payara-appserver-modules.notification-jms-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.notification-jms-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.external.]]
==== *org.glassfish.external.*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>management-api</groupId>
    <artifactId>org.glassfish.external.</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.ejb-mapping]]
==== *fish.payara.server.internal.persistence.cmp.ejb-mapping*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>ejb-mapping module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.ejb-mapping</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration-fragment]]
==== *fish.payara.server.internal.web.weld-integration-fragment*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>weld integration fragment</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration-fragment</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration]]
==== *fish.payara.server.internal.web.weld-integration*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>weld integration for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.glassfish.tyrus.container-grizzly-client]]
==== *org.glassfish.tyrus.container-grizzly-client*
**Version**: 2.1.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus grizzly client container</groupId>
    <artifactId>org.glassfish.tyrus.container-grizzly-client</artifactId>
    <version>2.1.3.payara-p1</version>
</dependency>
----
[[fish.payara.api.payara-api]]
==== *fish.payara.api.payara-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>payara-api</groupId>
    <artifactId>fish.payara.api.payara-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jakarta.persistence-api]]
==== *jakarta.persistence-api*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta persistence api jar</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[libpam4j-repackaged]]
==== *libpam4j-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.packager</groupId>
    <artifactId>libpam4j-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[libpam4j]]
==== *libpam4j*
**Version**: 1.11

[source,xml]
----
<dependency>
    <groupId>org.kohsuke</groupId>
    <artifactId>libpam4j</artifactId>
    <version>1.11</version>
</dependency>
----
[[fish.payara.server.core.packager.libpam4j-repackaged]]
==== *fish.payara.server.core.packager.libpam4j-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>libpam4j repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.libpam4j-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.packager.jmxremote_optional-repackaged]]
==== *fish.payara.server.core.packager.jmxremote_optional-repackaged*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>jmxremote_optional repackaged as a module</groupId>
    <artifactId>fish.payara.server.core.packager.jmxremote_optional-repackaged</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet-core</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.jms.admin]]
==== *fish.payara.server.internal.jms.admin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms admin</groupId>
    <artifactId>fish.payara.server.internal.jms.admin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.websocket-client-api]]
==== *jakarta.websocket-client-api*
**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta websocket - client api</groupId>
    <artifactId>jakarta.websocket-client-api</artifactId>
    <version>2.1.1</version>
</dependency>
----
[[xmpp-notifier-core]]
==== *xmpp-notifier-core*
**Version**: 2.0-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>xmpp-notifier-core</artifactId>
    <version>2.0-enterprise</version>
</dependency>
----
[[fish.payara.extensions.notifiers.xmpp-notifier-core]]
==== *fish.payara.extensions.notifiers.xmpp-notifier-core*
**Version**: 2.0.0.enterprise

[source,xml]
----
<dependency>
    <groupId>xmpp notifier implementation</groupId>
    <artifactId>fish.payara.extensions.notifiers.xmpp-notifier-core</artifactId>
    <version>2.0.0.enterprise</version>
</dependency>
----
[[fish.payara.server.internal.jms.core]]
==== *fish.payara.server.internal.jms.core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms module</groupId>
    <artifactId>fish.payara.server.internal.jms.core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-concurrent-plugin]]
==== *fish.payara.server.internal.admingui.console-concurrent-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>admin console concurrent plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-concurrent-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[gf-client-module]]
==== *gf-client-module*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>gf-client-module</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[angus-activation]]
==== *angus-activation*
**Version**: 1.1.0

[source,xml]
----
<dependency>
    <groupId>angus activation registries</groupId>
    <artifactId>angus-activation</artifactId>
    <version>1.1.0</version>
</dependency>
----
[[flashlight-framework]]
==== *flashlight-framework*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.flashlight</groupId>
    <artifactId>flashlight-framework</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[opentracing-adapter]]
==== *opentracing-adapter*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.payara-modules</groupId>
    <artifactId>opentracing-adapter</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.payara-modules.opentracing-adapter]]
==== *fish.payara.server.core.payara-modules.opentracing-adapter*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>opentracing adapter service</groupId>
    <artifactId>fish.payara.server.core.payara-modules.opentracing-adapter</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[amx-javaee]]
==== *amx-javaee*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>amx-javaee</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.amx-javaee]]
==== *fish.payara.server.core.common.amx-javaee*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>amx javaee</groupId>
    <artifactId>fish.payara.server.core.common.amx-javaee</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[org.igniterealtime.smack.extensions]]
==== *org.igniterealtime.smack.extensions*
**Version**: 4.3.4

[source,xml]
----
<dependency>
    <groupId>smack-extensions</groupId>
    <artifactId>org.igniterealtime.smack.extensions</artifactId>
    <version>4.3.4</version>
</dependency>
----
[[fish.payara.server.internal.admingui.jms-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.jms-notifier-console-plugin*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>jms notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.jms-notifier-console-plugin</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>cdi eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[jakarta.enterprise.lang-model]]
==== *jakarta.enterprise.lang-model*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.lang-model</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[jakarta.enterprise.lang-model]]
==== *jakarta.enterprise.lang-model*
**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>cdi language model</groupId>
    <artifactId>jakarta.enterprise.lang-model</artifactId>
    <version>4.0.1</version>
</dependency>
----
[[org.glassfish.metro.webservices-api-osgi]]
==== *org.glassfish.metro.webservices-api-osgi*
**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>metro web services api osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-api-osgi</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----
[[everit-json-schema]]
==== *everit-json-schema*
**Version**: 1.14.3

[source,xml]
----
<dependency>
    <groupId>com.github.erosb</groupId>
    <artifactId>everit-json-schema</artifactId>
    <version>1.14.3</version>
</dependency>
----
[[hazelcast-tpc-engine]]
==== *hazelcast-tpc-engine*
**Version**: 5.3.6

[source,xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-tpc-engine</artifactId>
    <version>5.3.6</version>
</dependency>
----
[[hazelcast]]
==== *hazelcast*
**Version**: 5.3.6

[source,xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>5.3.6</version>
</dependency>
----
[[hikaricp]]
==== *hikaricp*
**Version**: 4.0.3

[source,xml]
----
<dependency>
    <groupId>com.zaxxer</groupId>
    <artifactId>hikaricp</artifactId>
    <version>4.0.3</version>
</dependency>
----
[[classgraph]]
==== *classgraph*
**Version**: 4.8.158

[source,xml]
----
<dependency>
    <groupId>io.github.classgraph</groupId>
    <artifactId>classgraph</artifactId>
    <version>4.8.158</version>
</dependency>
----
[[json]]
==== *json*
**Version**: 20231013

[source,xml]
----
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20231013</version>
</dependency>
----
[[snakeyaml-engine]]
==== *snakeyaml-engine*
**Version**: 2.6

[source,xml]
----
<dependency>
    <groupId>org.snakeyaml</groupId>
    <artifactId>snakeyaml-engine</artifactId>
    <version>2.6</version>
</dependency>
----
[[fish.payara.server.core.flashlight.framework]]
==== *fish.payara.server.core.flashlight.framework*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>flashlight-framework</groupId>
    <artifactId>fish.payara.server.core.flashlight.framework</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[com.hazelcast]]
==== *com.hazelcast*
**Version**: 5.3.6

[source,xml]
----
<dependency>
    <groupId>hazelcast(core)</groupId>
    <artifactId>com.hazelcast</artifactId>
    <version>5.3.6</version>
</dependency>
----
[[org.jxmpp.util-cache]]
==== *org.jxmpp.util-cache*
**Version**: 0.6.4

[source,xml]
----
<dependency>
    <groupId>jxmpp-util-cache</groupId>
    <artifactId>org.jxmpp.util-cache</artifactId>
    <version>0.6.4</version>
</dependency>
----
[[fish.payara.server.appclient.gf-client-module]]
==== *fish.payara.server.appclient.gf-client-module*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>client osgi module (including acc)</groupId>
    <artifactId>fish.payara.server.appclient.gf-client-module</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[hk2]]
==== *hk2*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.hk2.hk2]]
==== *org.glassfish.hk2.hk2*
**Version**: 3.0.1.payara-p4

[source,xml]
----
<dependency>
    <groupId>hk2 module of hk2 itself</groupId>
    <artifactId>org.glassfish.hk2.hk2</artifactId>
    <version>3.0.1.payara-p4</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 3.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-grizzly2-http</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>3.1.7.payara-p1</version>
</dependency>
----
[[fish.payara.extensions.certificate-management.console-plugin]]
==== *fish.payara.extensions.certificate-management.console-plugin*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>admin console plugin for certificate management</groupId>
    <artifactId>fish.payara.extensions.certificate-management.console-plugin</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[glassfish-api]]
==== *glassfish-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.common</groupId>
    <artifactId>glassfish-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.common.glassfish-api]]
==== *fish.payara.server.core.common.glassfish-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>public apis of glassfish</groupId>
    <artifactId>fish.payara.server.core.common.glassfish-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[microprofile-common]]
==== *microprofile-common*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-common</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[web-embed-api]]
==== *web-embed-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.core.web</groupId>
    <artifactId>web-embed-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[fish.payara.server.core.web.embed-api]]
==== *fish.payara.server.core.web.embed-api*
**Version**: 6.19.0

[source,xml]
----
<dependency>
    <groupId>glassfish web container embedded apis</groupId>
    <artifactId>fish.payara.server.core.web.embed-api</artifactId>
    <version>6.19.0</version>
</dependency>
----
[[jacc.provider.inmemory]]
==== *jacc.provider.inmemory*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>jacc.provider.inmemory</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[fish.payara.server.internal.security.jacc.provider.inmemory]]
==== *fish.payara.server.internal.security.jacc.provider.inmemory*
**Version**: 6.18.0

[source,xml]
----
<dependency>
    <groupId>a pluggable inmemory jacc provider</groupId>
    <artifactId>fish.payara.server.internal.security.jacc.provider.inmemory</artifactId>
    <version>6.18.0</version>
</dependency>
----
[[org.jboss.weld.osgi-bundle]]
==== *org.jboss.weld.osgi-bundle*
**Version**: 5.0.1.final

[source,xml]
----
<dependency>
    <groupId>weld osgi bundle</groupId>
    <artifactId>org.jboss.weld.osgi-bundle</artifactId>
    <version>5.0.1.final</version>
</dependency>
----
